/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TELEMETRY_PB_H_INCLUDED
#define PB_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ActivateRequest {
    char node_id[32];
    char secretkey[32];
    char gps[64];
    float soc;
    char fw_ver[32];
    char hw_ver[32];
    char sim_mod_sn[32];
    char sim_card_sn[32];
    char chassis_ver[32];
} ActivateRequest;

typedef struct _GpsUpdateRequest {
    char node_id[32];
    char gps[64];
    float soc;
    char fw_ver[32];
} GpsUpdateRequest;

typedef struct _ReadingRequest {
    char node_id[32];
    char m_type[16];
    pb_size_t readings_count;
    float readings[25];
    uint64_t session;
} ReadingRequest;

typedef struct _StringValue {
    char value[256];
} StringValue;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ActivateRequest_init_default             {"", "", "", 0, "", "", "", "", ""}
#define GpsUpdateRequest_init_default            {"", "", 0, ""}
#define ReadingRequest_init_default              {"", "", 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}
#define StringValue_init_default                 {""}
#define ActivateRequest_init_zero                {"", "", "", 0, "", "", "", "", ""}
#define GpsUpdateRequest_init_zero               {"", "", 0, ""}
#define ReadingRequest_init_zero                 {"", "", 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}
#define StringValue_init_zero                    {""}

/* Field tags (for use in manual encoding/decoding) */
#define ActivateRequest_node_id_tag              1
#define ActivateRequest_secretkey_tag            2
#define ActivateRequest_gps_tag                  3
#define ActivateRequest_soc_tag                  4
#define ActivateRequest_fw_ver_tag               5
#define ActivateRequest_hw_ver_tag               6
#define ActivateRequest_sim_mod_sn_tag           7
#define ActivateRequest_sim_card_sn_tag          8
#define ActivateRequest_chassis_ver_tag          9
#define GpsUpdateRequest_node_id_tag             1
#define GpsUpdateRequest_gps_tag                 2
#define GpsUpdateRequest_soc_tag                 3
#define GpsUpdateRequest_fw_ver_tag              4
#define ReadingRequest_node_id_tag               1
#define ReadingRequest_m_type_tag                2
#define ReadingRequest_readings_tag              3
#define ReadingRequest_session_tag               4
#define StringValue_value_tag                    1

/* Struct field encoding specification for nanopb */
#define ActivateRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   node_id,           1) \
X(a, STATIC,   SINGULAR, STRING,   secretkey,         2) \
X(a, STATIC,   SINGULAR, STRING,   gps,               3) \
X(a, STATIC,   SINGULAR, FLOAT,    soc,               4) \
X(a, STATIC,   SINGULAR, STRING,   fw_ver,            5) \
X(a, STATIC,   SINGULAR, STRING,   hw_ver,            6) \
X(a, STATIC,   SINGULAR, STRING,   sim_mod_sn,        7) \
X(a, STATIC,   SINGULAR, STRING,   sim_card_sn,       8) \
X(a, STATIC,   SINGULAR, STRING,   chassis_ver,       9)
#define ActivateRequest_CALLBACK NULL
#define ActivateRequest_DEFAULT NULL

#define GpsUpdateRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   node_id,           1) \
X(a, STATIC,   SINGULAR, STRING,   gps,               2) \
X(a, STATIC,   SINGULAR, FLOAT,    soc,               3) \
X(a, STATIC,   SINGULAR, STRING,   fw_ver,            4)
#define GpsUpdateRequest_CALLBACK NULL
#define GpsUpdateRequest_DEFAULT NULL

#define ReadingRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   node_id,           1) \
X(a, STATIC,   SINGULAR, STRING,   m_type,            2) \
X(a, STATIC,   REPEATED, FLOAT,    readings,          3) \
X(a, STATIC,   SINGULAR, UINT64,   session,           4)
#define ReadingRequest_CALLBACK NULL
#define ReadingRequest_DEFAULT NULL

#define StringValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   value,             1)
#define StringValue_CALLBACK NULL
#define StringValue_DEFAULT NULL

extern const pb_msgdesc_t ActivateRequest_msg;
extern const pb_msgdesc_t GpsUpdateRequest_msg;
extern const pb_msgdesc_t ReadingRequest_msg;
extern const pb_msgdesc_t StringValue_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ActivateRequest_fields &ActivateRequest_msg
#define GpsUpdateRequest_fields &GpsUpdateRequest_msg
#define ReadingRequest_fields &ReadingRequest_msg
#define StringValue_fields &StringValue_msg

/* Maximum encoded size of messages (where known) */
#define ActivateRequest_size                     301
#define GpsUpdateRequest_size                    136
#define ReadingRequest_size                      186
#define StringValue_size                         258
#define TELEMETRY_PB_H_MAX_SIZE                  ActivateRequest_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
