/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "telemetry.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ActivateRequest, ActivateRequest, 2)


PB_BIND(GpsUpdateRequest, GpsUpdateRequest, AUTO)


PB_BIND(ReadingRequest, ReadingRequest, AUTO)


PB_BIND(StringValue, StringValue, 2)



