/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "telemetry.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ActivateRequest, ActivateRequest, AUTO)


PB_BIND(Manf, Manf, AUTO)


PB_BIND(GpsUpdateRequest, GpsUpdateRequest, AUTO)


PB_BIND(OtaStatus, OtaStatus, AUTO)


PB_BIND(Battery, Battery, AUTO)


PB_BIND(Position, Position, AUTO)


PB_BIND(NetInfo, NetInfo, AUTO)


PB_BIND(NetStat, NetStat, AUTO)


PB_BIND(ReadingRequest, ReadingRequest, AUTO)


PB_BIND(StringValue, StringValue, 2)


PB_BIND(HealthRequest, HealthRequest, AUTO)


PB_BIND(ConfigRequest, ConfigRequest, AUTO)


PB_BIND(ConfigResponse, ConfigResponse, AUTO)



